### ISSUE TITLE
Reporte de TextBox

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Aricel117#2]
[Reporte TextBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Aricel117/files/6357160/Reporte.TextBox.pdf)

**Comment by CxrlosMX** [comment]
Muy buen reporte compañero, felicidades :)
Calificación obtenida: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
